<a href="https://colab.research.google.com/github/ktgirl38/CSC-402/blob/main/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
filename = '/content/drive/MyDrive/olympic_medals.csv'
df=pd.read_csv(filename)

a) Find the size of the data frame. How many rows, how many columns? 2394 rows, 8 columns

In [ ]:
df.shape

(2394, 8)

b) Use the appropriate function to report the data types for all columns.

In [ ]:
df.dtypes

Gender         object
Event          object
Location       object
Year            int64
Medal          object
Name           object
Nationality    object
Result         object
dtype: object

c) Find how many unique cities matches were held at. (Hint: unique( ). For instance, the following example tells how many unique Events held)
len(medals['Event'].unique())

In [ ]:
len(df["Location"].unique())

23

d) Find how many medals the USA team won in total.

In [ ]:
len(df[df['Nationality']=="USA"])

638

e) Find the total number of medals for each Nationality. (Hint: please search  or groupby() function with count. For instance, the following example counts at how many locations each event was held. )
medals.groupby(by='Event')['Location'].count()

In [ ]:
df.groupby(by='Nationality')['Medal'].count()

Nationality
ALG      9
ARG      4
AUS     57
AUT      4
BAH     12
      ...
URS    131
USA    638
VEN      2
YUG      1
ZAM      1
Name: Medal, Length: 97, dtype: int64